### ISSUE TITLE
Points pour la fonctionnalité de la nouvelle page (classement dans le nouveau Lab0)

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-enonce-lab0#25]
Ajouter des points pour s'assurer que la nouvelle page supporte la même fonctionnalité que la page initiale.

**Comment by fuhrmanator** [comment]
Dans #18 la nouvelle page est une autre vue. Alors, ce problème n'existe pas.

**Comment by RubenLaden** [comment]
Le problème existe toujours est maintenant "Ajouter des points pour s'assurer que la nouvelle page affiche correctement le classement."
