### ISSUE TITLE
Changement de page

### ISSUE THREAD

**Issue by yvanross** [profcfuhrmanets/log210-enonce-lab0#29]
Refaire et documenter l’exemple de changement  de page au lab0

**Comment by fuhrmanator** [comment]
@yvanross connais-tu un exemple appliqué dans une solution pour le lab 1 dont on peut s'inspirer? 

Sinon, je pensais faire dans le squelette un template PUG avec une barre de navigation, avec 2 pages:

- jouer.html: Démarrer jeu / Jouer / Terminer jeu (ce dernier n'est pas complet)
- stats.html: Afficher statistiques

Dans le lab0 ils ont à compléter Terminer jeu. Ça simplifie le tout. 

Pour le calcul de classement dans les statistiques, plutôt que de faire ça dans PUG (compliqué), on peut leur demander d'ajouter un getter `ratio()` dans la class Joueur (modification de la classe du domaine) qui est en fait un attribut dérivé `/ratio`.

**Comment by fuhrmanator** [comment]
Fixed dans #31
