### ISSUE TITLE
100% de couverture est mentionné 2 fois dans le READMe.md

### ISSUE THREAD

**Issue by fuhrmanator** [profcfuhrmanets/log210-enonce-lab0#53]
Clarifier la commande qui nécessite le 100% de couverture (possiblement supprimer la mention première)

**Comment by fuhrmanator** [comment]
`npx jest` est nécessaire pour avoir 100% de couverture puisque certains tests font partie de ceux nommé `lab0`

Quelle colonne de coverage? statement? Branch? function?

**Comment by elainesoucy** [comment]
Peut-être plutôt simplement remplacer la partie de phrase "pour la partie fonctionnalité" par "avec la commande `npx jest --colors --coverage`" au point 10 dans la phrase "Assurez-vous qu'aucun test n'est en échec et que la couverture de test est de 100% pour la partie fonctionnalité."
