### ISSUE TITLE
Est-ce que la démo vidéo est utile si le laboratoire est corrigé automatiquement?

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/log210-enonce-lab0#9]

**Comment by elainesoucy** [comment]
Personnellement, ça m'a servi une seule fois pour un étudiant. J'avais un étudiant qui avait tout mauvais côté front-end dans le labo 0. En regardant la vidéo, tout fonctionnait. J'ai donc essayé dans un navigateur différent, ce qui a corrigé le problème.
Autrement, ça ne m'a jamais été utile. Dans tous les cas, je ne crois pas que ce soit vraiment pertinent. Il faudrait simplement se souvenir qu'il arrive que le front-end fonctionne mal pour certaines équipes dans certains navigateurs et donc de penser à l'essayer dans un autre navigateur.
Pour le laboratoire 1, les étudiants font la présentation devant nous en temps réel. S'il y a un problème, on le voit en même temps qu'eux lors de la correction.
